apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-config
  namespace: default
data:
  wg0.conf: |
    [Interface]
    PrivateKey = SERVER_PRIVATE_KEY
    ListenPort = 51820
    MTU = 1362
    PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    Address = 192.168.4.1/24

    [Peer]
    PublicKey = CLIENT_PUBLIC_KEY
    AllowedIPS = 192.168.4.2/32
