---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-service
spec:
  ports:
    - port: 51820
      targetPort: 51820
      nodePort: 30443
      protocol: UDP
  selector:
    app: wireguard-vpn
  type: NodePort

